# Generated by Django 5.2 on 2025-05-15 07:30

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Interface',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True, verbose_name='Название')),
                ('subtitle', models.CharField(blank=True, max_length=100, verbose_name='Подзаголовок')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='interfaces/', verbose_name='Лого')),
                ('illustration', models.ImageField(blank=True, null=True, upload_to='interfaces/', verbose_name='Иллюстрация')),
            ],
            options={
                'verbose_name': 'Интерфейс',
                'verbose_name_plural': 'Интерфейсы',
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='InterfaceSubCatalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True, verbose_name='Название Подкаталога')),
                ('order_position', models.PositiveIntegerField(default=1, help_text='Чем меньше, тем выше Подкаталог в Каталоге.', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Позиция Подкаталога в Каталоге')),
            ],
            options={
                'verbose_name': 'Подкаталог Интерфейсов',
                'verbose_name_plural': 'Подкаталоги Интерфейсов',
                'ordering': ('order_position',),
            },
        ),
        migrations.CreateModel(
            name='InterfaceCatalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_position', models.PositiveIntegerField(default=1, help_text='Чем меньше, тем выше Интерфейс в Подкаталоге.', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Позиция Интерфейса в Подкаталоге')),
                ('interface', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interfaces', to='interfaces.interface', verbose_name='Интерфейс')),
                ('subcatalog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcatalogs', to='interfaces.interfacesubcatalog', verbose_name='Подкаталог Интерфейсов')),
            ],
            options={
                'verbose_name': 'Связь Интерфейса и Подкаталога',
                'verbose_name_plural': 'Связи Интерфейсов и Подкаталогов',
                'ordering': ('order_position',),
            },
        ),
        migrations.AddField(
            model_name='interface',
            name='subcatalogs',
            field=models.ManyToManyField(blank=True, related_name='interfaces', through='interfaces.InterfaceCatalog', through_fields=('interface', 'subcatalog'), to='interfaces.interfacesubcatalog', verbose_name='Подкаталоги'),
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название')),
                ('subtitle', models.CharField(blank=True, max_length=100, verbose_name='Подзаголовок')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='roles/', verbose_name='Лого')),
                ('illustration', models.ImageField(blank=True, null=True, upload_to='roles/', verbose_name='Иллюстрация')),
                ('order_position', models.PositiveIntegerField(default=1, help_text='Чем меньше, тем выше Роль в Интерфейсе.', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Очередь Роли')),
                ('interface', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='interfaces.interface', verbose_name='Интерфейс')),
            ],
            options={
                'verbose_name': 'Роль',
                'verbose_name_plural': 'Роли',
            },
        ),
        migrations.CreateModel(
            name='Function',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job', models.CharField(max_length=50, verbose_name='Название Ключевой Функции')),
                ('description', models.TextField(blank=True, verbose_name='Описание Ключевой Функции')),
                ('order_position', models.PositiveIntegerField(default=1, help_text='Чем меньше, тем выше Функция в Роли.', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Очередь Функции')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='functions', to='interfaces.role', verbose_name='Роль Пользователя')),
            ],
            options={
                'verbose_name': 'Функция',
                'verbose_name_plural': 'Функции',
            },
        ),
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название Истории')),
                ('got_wanted', models.BooleanField(help_text='Укажите, является данная История успешной или отказной.', verbose_name='Пользователь получил желаемый результат')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('order_position', models.PositiveIntegerField(default=1, help_text='Чем меньше, тем выше История в Функции.', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Очередь Истории')),
                ('function', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stories', to='interfaces.function', verbose_name='Ключевая Функция')),
            ],
            options={
                'verbose_name': 'История',
                'verbose_name_plural': 'Истории',
            },
        ),
        migrations.CreateModel(
            name='StartPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=100, verbose_name='В момент начала')),
                ('story', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='start_point', to='interfaces.story', verbose_name='История')),
            ],
            options={
                'verbose_name': 'Старт',
                'verbose_name_plural': 'Старт',
            },
        ),
        migrations.CreateModel(
            name='StoryAcceptor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=100, verbose_name='Акцептор')),
                ('order_position', models.PositiveIntegerField(default=1, help_text='Чем меньше, тем выше в списке данный Акцептор.', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Очередь Акцептора')),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acceptors', to='interfaces.story', verbose_name='История')),
            ],
            options={
                'verbose_name': 'Акцептор',
                'verbose_name_plural': 'Акцепторы',
            },
        ),
        migrations.CreateModel(
            name='StoryContext',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(help_text='Важный нюанс ситуации, в которой находится Пользователь.', max_length=100, verbose_name='Когда')),
                ('order_position', models.PositiveIntegerField(default=1, help_text='Чем меньше, тем выше в списке данная строка.', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Очередь Ситуации')),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='context_points', to='interfaces.story', verbose_name='История')),
            ],
            options={
                'verbose_name': 'Cитуация',
                'verbose_name_plural': 'Предыстория',
            },
        ),
        migrations.AddConstraint(
            model_name='interfacecatalog',
            constraint=models.UniqueConstraint(fields=('interface', 'subcatalog'), name='unique_interface_subcatalog'),
        ),
        migrations.AddConstraint(
            model_name='function',
            constraint=models.UniqueConstraint(fields=('role', 'job'), name='unique_role_function'),
        ),
        migrations.AddConstraint(
            model_name='story',
            constraint=models.UniqueConstraint(fields=('function', 'title'), name='unique_function_story'),
        ),
    ]
